trigger:
  - main
  - develop

pool:
  name: Default
  demands:
    - agent.name -equals master-node

variables:
  imageName: "asian-food-web-prod"
  containerRegistry: "docker.io/cheulong"

stages:
  - stage: Test
    displayName: Test App
    jobs:
      - job: TestApp
        displayName: Test App
        steps:
          - task: UseNode@1
            inputs:
              version: '23.x'
          - script: |
              npm ci
            displayName: 'Install Dependencies'
          - script: |
              npx playwright install
            displayName: "Install Playwright Dependencies"
          - script: |
              npm run lint
            displayName: 'Run Lint'
          - script: |
              npm run test
            displayName: "Run Unit Tests"
          - script: |
              npm run playwright
            displayName: 'Run E2E Tests'
  - stage: Build_Push
    displayName: Build and Push Docker Image
    dependsOn: Test
    jobs:
      - job: BuildAndPush
        displayName: Build and Push Docker Image
        steps:
        - task: DockerInstaller@0
          inputs:
            dockerVersion: '17.09.0-ce'
        - task: Docker@2
          inputs:
            containerRegistry: 'DockerHubConnection'
            repository: 'cheulong/asian-food-web-prod'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile.prod'
