FROM node:23-bookworm-slim AS build

WORKDIR /app

COPY package*.json ./

# Define build arguments for environment variables
ARG VITE_API_URL_ARG

# Set environment variables during the build process
ENV VITE_API_URL=$VITE_API_URL_ARG

RUN npm ci --omit=dev

COPY . .

RUN npm run build

# Production Stage
FROM nginx:1.27.4-alpine-slim AS production
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]